spring:
  application:
    name: 34-sbms-greetapi-16
    
  boot:
    admin:
      client:
        url: http://localhost:1111/
        

  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        